extends Node

signal play_audio(audio)
signal player_die
signal player_damaged(damage)
signal achievement(ach)
signal unlock(item)
signal ach_popup_finished
signal coin_pickup(amount)
signal inventory_changed
signal inventory_item_moved
signal max_health_changed(amount)
signal coins_saved
signal pickup_item_recieved(item)
signal room_cleared
signal entered_new_floor(number)
signal entered_new_room(number)
signal new_run
signal freeing_orphans
signal topping_saved
signal topping_killed
signal item_sold(amount)
signal enemy_defeated(enemy)
